version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: blogapp-postgres
    environment:
      POSTGRES_DB: blogApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blogapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blogApp"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blogapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blogapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - blogapp-network
    depends_on:
      postgres:
        condition: service_healthy

  blogapp:
    build: .
    container_name: blogapp-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blogApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - blogapp-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
  pgadmin_data:

networks:
  blogapp-network:
    driver: bridge 